version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  verify-2fa:
    lang: python3-http
    handler: ./verify-2fa
    image: jinfanti/verify-2fa:latest
    environment:
      FERNET_KEY: "rblAPTuZKdNT2MnRFk9wLhVE4LJrcoT2TdtPF-FtHfo="
      DATABASE_URL: "postgres://postgres:cJNzEtOleI@cofrap-db-postgresql.default.svc.cluster.local:5432/postgres"
