version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  generate-2fa:
    lang: python3-http
    handler: ./generate-2fa
    image: jinfanti/generate-2fa:latest
    environment:
      FERNET_KEY: "dtn3GvA6FGTVBHLgtQMzdA1WUpY6AriWmKA0MG-faoU="
      DATABASE_URL: "postgres://postgres:gMg50xmq03@cofrap-db-postgresql.default.svc.cluster.local:5432/postgres"

